# Generated by Django 5.1.2 on 2024-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('Name', models.CharField(max_length=15)),
                ('Aadharno', models.IntegerField(primary_key='Aadharno', serialize=False)),
                ('address', models.CharField(max_length=20)),
                ('loanamt', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
